"""`repolens completion bash|zsh|fish`: shell completion scripts generated from the argparse parser.

Generated rather than hand-written, so a new command or option is completed without
anyone remembering to update a script.
"""

from __future__ import annotations

import argparse
import shlex
import sys

from repolens.commands._common import add_command

NAME = "completion"
SHELLS = ("bash", "zsh", "fish")


def register(subparsers, common):
    p = add_command(
        subparsers,
        NAME,
        common,
        "Print a shell completion script",
        "Cetak script tab-completion untuk shell",
    )
    p.add_argument("shell", choices=SHELLS)
    return p


def run(args) -> int:
    from repolens.cli import build_parser  # imported here: cli imports this module

    sys.stdout.write(script(args.shell, build_parser()))
    return 0


def _tree(parser: argparse.ArgumentParser) -> dict:
    """The parser as a tree of what can be typed at each level:

    {"options": [...], "choices": {option: [values]}, "help": {name: text},
     "commands": {name: subtree}, "words": [values of a positional with fixed choices]}"""
    node = {"options": [], "choices": {}, "help": {}, "commands": {}, "words": []}
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            helps = {a.dest: a.help or "" for a in action._choices_actions}
            for name, sub in action.choices.items():
                node["commands"][name] = _tree(sub)
                node["help"][name] = helps.get(name, "")
        elif not action.option_strings:
            node["words"] += [str(c) for c in action.choices or []]
        else:
            long = [o for o in action.option_strings if o.startswith("--")] or action.option_strings
            node["options"] += long
            for option in long:
                node["help"][option] = action.help or ""
                if action.choices:
                    node["choices"][option] = [str(c) for c in action.choices]
    return node


def _walk(node: dict, path: tuple[str, ...] = ()):
    yield path, node
    for name, sub in node["commands"].items():
        yield from _walk(sub, path + (name,))


def bash(parser: argparse.ArgumentParser) -> str:
    """A bash completion function: sub-commands, options, and the values of options with fixed
    choices; anything else falls back to file names."""
    tree = _tree(parser)
    nodes = list(_walk(tree))
    known = " | ".join(shlex.quote(" ".join(p)) for p, _ in nodes if p)
    cases, value_cases = [], []
    for path, node in nodes:
        key = shlex.quote(" ".join(path))
        cases.append(
            f"    {key}) commands={shlex.quote(' '.join([*node['commands'], *node['words']]))}; "
            f"options={shlex.quote(' '.join(node['options']))} ;;"
        )
        for option, values in node["choices"].items():
            value_cases.append(
                f"    {shlex.quote(' '.join(path) + ' ' + option)}) "
                f"values={shlex.quote(' '.join(values))} ;;"
            )
    return f"""# repolens completion for bash (generated by `repolens completion bash`)
_repolens_completion() {{
  local cur=${{COMP_WORDS[COMP_CWORD]}} prev=${{COMP_WORDS[COMP_CWORD-1]}} path="" i word next
  for ((i = 1; i < COMP_CWORD; i++)); do
    word=${{COMP_WORDS[i]}}
    next="${{path:+$path }}$word"
    case "$next" in
      {known}) path=$next ;;
    esac
  done
  local commands="" options="" values=""
  case "$path" in
{chr(10).join(cases)}
  esac
  case "$path $prev" in
{chr(10).join(value_cases) or "    __none__) ;;"}
  esac
  if [[ -n $values ]]; then
    COMPREPLY=($(compgen -W "$values" -- "$cur"))
  elif [[ $cur == -* ]]; then
    COMPREPLY=($(compgen -W "$options" -- "$cur"))
  elif [[ -n $commands ]]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
  fi
}}
complete -o default -F _repolens_completion repolens
"""


def zsh(parser: argparse.ArgumentParser) -> str:
    return (
        "# repolens completion for zsh (generated by `repolens completion zsh`)\n"
        "(( $+functions[compdef] )) || { autoload -U compinit && compinit }\n"
        "autoload -U +X bashcompinit && bashcompinit\n" + bash(parser).split("\n", 1)[1]
    )


def fish(parser: argparse.ArgumentParser) -> str:
    """fish `complete` lines, one per command and option, with their help text as description."""
    tree = _tree(parser)
    lines = [
        "# repolens completion for fish (generated by `repolens completion fish`)",
        "complete -c repolens -f",
    ]

    def quote(text: str) -> str:
        return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"

    for path, node in _walk(tree):
        if not path:
            condition = "__fish_use_subcommand"
        else:
            condition = f"__fish_seen_subcommand_from {path[-1]}"
            if len(path) == 1 and node["commands"]:
                condition += f"; and not __fish_seen_subcommand_from {' '.join(node['commands'])}"
        for name in node["commands"]:
            lines.append(
                f"complete -c repolens -n {quote(condition)} -a {name} -d "
                f"{quote(node['help'][name])}"
            )
        if node["words"]:
            lines.append(
                f"complete -c repolens -n {quote(condition)} -a {quote(' '.join(node['words']))}"
            )
        for option in node["options"]:
            flag = f"-l {option[2:]}" if option.startswith("--") else f"-s {option[1:]}"
            values = node["choices"].get(option)
            extra = f" -x -a {quote(' '.join(values))}" if values else ""
            lines.append(
                f"complete -c repolens -n {quote(condition)} {flag}{extra} -d "
                f"{quote(node['help'][option])}"
            )
    # sources and scan.json files are paths
    lines.append(
        "complete -c repolens -n '__fish_seen_subcommand_from scan doctor init export diff' -F"
    )
    return "\n".join(lines) + "\n"


def script(shell: str, parser: argparse.ArgumentParser) -> str:
    return {"bash": bash, "zsh": zsh, "fish": fish}[shell](parser)
